version: '2'
services:
  eureka-service:
     image: akaczmarek/eureka-service:${BUILD_NAME}
     mem_limit: 3000m
     ports:
         - "8761:8761"
  config-service:
      image: akaczmarek/config-service:${BUILD_NAME}
      mem_limit: 3000m
      ports:
         - "8888:8888"
      links:
         - "eureka-service:eureka-service"
      environment:
         EUREKASERVER_URI: "http://eureka-service:8761/eureka/"
         EUREKASERVER_PORT: "8761"
         ENCRYPT_KEY: "SPRING_CLOUD_DEV"

  zuul-service:
    image: akaczmarek/zuul-service:${BUILD_NAME}
    mem_limit: 3000m
    ports:
      - "5555:5555"
    links:
      - "config-service:config-service"
      - "eureka-service:eureka-service"
    environment:
      PROFILE: "aws-dev"
      SERVER_PORT: "5555"
      CONFIGSERVER_URI: "http://config-service:8888"
      EUREKASERVER_URI: "http://eureka-service:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      CONFIGSERVER_PORT:        "8888"


  authentication-service:
      image: akaczmarek/authentication-service:${BUILD_NAME}
      mem_limit: 3000m
      ports:
        - "8901:8901"
      links:
        - "config-service:config-service"
        - "eureka-service:eureka-service"
        - "zuul-service:zuul-service"
      environment:
        PROFILE: "aws-dev"
        SERVER_PORT: "8901"
        DATABASE_PORT:     5432
        CONFIGSERVER_PORT: 8888
        EUREKASERVER_PORT: 8761
        CONFIGSERVER_URI: "http://config-service:8888"
        EUREKASERVER_URI: "http://eureka-service:8761/eureka/"
        ENCRYPT_KEY:       "SPRING_CLOUD_DEV"
