version: '2'
services:
  eureka-service:
     image: homesamples/eureka-service:homesamples
     ports:
         - "8761:8761"
  config-service:
      image: homesamples/config-service:homesamples
      ports:
         - "8888:8888"
      environment:
         EUREKASERVER_URI: "http://eureka-service:8761/eureka/"
         EUREKASERVER_PORT: "8761"
         ENCRYPT_KEY: "SPRING_CLOUD_DEV"

  zuul-service:
    image: homesamples/zuul-service:homesamples
    ports:
      - "5555:5555"
    environment:
      PROFILE: "aws-dev"
      SERVER_PORT: "5555"
      CONFIGSERVER_URI: "http://config-service:8888"
      EUREKASERVER_URI: "http://eureka-service:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      CONFIGSERVER_PORT:        "8888"


  authentication-service:
      image: homesamples/authentication-service:homesamples
      ports:
        - "8901:8901"
      environment:
        PROFILE: "aws-dev"
        SERVER_PORT: "8901"
        DATABASE_PORT:     5432
        CONFIGSERVER_PORT: 8888
        EUREKASERVER_PORT: 8761
        CONFIGSERVER_URI: "http://config-service:8888"
        EUREKASERVER_URI: "http://eureka-service:8761/eureka/"
        ENCRYPT_KEY:       "SPRING_CLOUD_DEV"
