#Setting the logging levels for the service
logging:
  level:
    com.netflix: WAR
    org.springframework.web: WAR
    home.sample: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

server:
  port: 8901
  contextPath:   /auth

security:
  oauth2:
    resource:
      filter-order: 3

signing.key: "qazwsx!2"
