#Default port is 8761
server:
  port: 8761

#Setting the logging levels for the service
logging:
  level:
    org.springframework: ERROR

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
  serviceUrl:
    defaultZone: http://localhost:8761  
