server:
   port: 8888
spring:
  profiles:
    active: native
  cloud:
     config:
      discovery:
        enabled: true
      server:
           native:
               searchLocations: classpath:config/,classpath:config/about-service



